version: '3.8'

networks:
  # Specify the network for bridging
  orbiter2:
    driver: bridge

services:
  frontend:
    build: ./
    # command: yarn run dev
    environment:
      NODE_ENV: production # development production
    #   BACKEND_API: 'http://ec2-18-177-135-205.ap-northeast-1.compute.amazonaws.com:3002/'
    # volumes:
    # - './frontend:/app'
    ports:
      - '8001:80'
    # restart: always
    networks:
      - orbiter2
